### ISSUE TITLE
.luacompleterc has no effect

### ISSUE THREAD

**Issue by ThaisRobba** [dapetcu21/atom-autocomplete-lua#3]
I've been trying to add some entries to my .luacompleterc but nothing seems to get triggered. For example:

``` json
{
  "global": {
    "type": "table",
    "fields": {
      "counter": {
        "type": "number"
      }
    }
  }
}
```

This should work but I get no autocomplete suggestions. The rc file is in my project root, I have tried reloading Atom... am I doing something wrong?

Runnning on: Linux, Atom 1.11.2

PS: I freaking love this plugin, great work!

**Comment by dapetcu21** [comment]
I can't seem to be able to reproduce. I tried adding your `.luacompleterc` in my project root and it works. Is the file you're trying to edit saved or untitled? For it to work, the file must be saved somewhere inside the directory where you have `.luacompleterc`.

I'll try on Linux tomorrow, but I doubt there would be anything different. (I'm on OS X)

**Comment by ThaisRobba** [comment]
Files are saved and within the project. Attached a screenie of the file structure:

![captura de tela de 2016-10-23 19-28-33](https://cloud.githubusercontent.com/assets/597287/19629592/06c1cae4-9957-11e6-9f8a-3d34b9ba5b52.png)

**Comment by dapetcu21** [comment]
That's weird. Can you confirm this happens with an empty project? Like, just the `.luacompleterc` and a lua file?

Also, if you're interested in debugging, you can open the dev tools and place breakpoints in [lib/options/luacompleterc.js](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/options/luacompleterc.js) to try to find out what's happening there. The code is pretty straightforward. Only thing to watch out is that stepping behaves a little funky in async and generator functions.

**Comment by ThaisRobba** [comment]
Apparently it is a problem with the community package of Atom, in Arch Linux. Using the package in AUR fixed the issue. Sorry about that! :-)
