### ISSUE TITLE
[Question] Why number keys are not supported?

### ISSUE THREAD

**Issue by winterwolf** [dapetcu21/atom-autocomplete-lua#31]
Is there a chance that they will be supported in the future?

**Comment by dapetcu21** [comment]
What do you mean by number keys?

**Comment by winterwolf** [comment]
@dapetcu21 lua can use any types of values as keys for tables, but your plugin support only string keys.

**Comment by winterwolf** [comment]
https://github.com/dapetcu21/atom-autocomplete-lua#tables

> Even though Lua allows indexing tables with any value, only string keys are supported for autocompletion purposes.

**Comment by dapetcu21** [comment]
Oh, right, number table keys. Not sure why I didn't support them, but I'm not really maintaining this project anymore :(

**Comment by winterwolf** [comment]
Ok, thank you :)
